/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatisticsRouteImport } from './routes/Statistics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BiRouteImport } from './routes/bi'
import { Route as DataanalystRouteImport } from './routes/dataanalyst'
import { Route as ExcelRouteImport } from './routes/excel'
import { Route as InterviewQuestionsRouteImport } from './routes/interview-questions'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PythonRouteImport } from './routes/python'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as RoadmapsSlugRouteImport } from './routes/roadmaps.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/Statistics',
  path: '/Statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const DataanalystRoute = DataanalystRouteImport.update({
  id: '/dataanalyst',
  path: '/dataanalyst',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelRoute = ExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewQuestionsRoute = InterviewQuestionsRouteImport.update({
  id: '/interview-questions',
  path: '/interview-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsSlugRoute = RoadmapsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoadmapsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Statistics': typeof StatisticsRoute
  '/about': typeof AboutRoute
  '/bi': typeof BiRoute
  '/dataanalyst': typeof DataanalystRoute
  '/excel': typeof ExcelRoute
  '/interview-questions': typeof InterviewQuestionsRoute
  '/practice': typeof PracticeRoute
  '/projects': typeof ProjectsRoute
  '/python': typeof PythonRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql': typeof SqlRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Statistics': typeof StatisticsRoute
  '/about': typeof AboutRoute
  '/bi': typeof BiRoute
  '/dataanalyst': typeof DataanalystRoute
  '/excel': typeof ExcelRoute
  '/interview-questions': typeof InterviewQuestionsRoute
  '/practice': typeof PracticeRoute
  '/projects': typeof ProjectsRoute
  '/python': typeof PythonRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql': typeof SqlRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Statistics': typeof StatisticsRoute
  '/about': typeof AboutRoute
  '/bi': typeof BiRoute
  '/dataanalyst': typeof DataanalystRoute
  '/excel': typeof ExcelRoute
  '/interview-questions': typeof InterviewQuestionsRoute
  '/practice': typeof PracticeRoute
  '/projects': typeof ProjectsRoute
  '/python': typeof PythonRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql': typeof SqlRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Statistics'
    | '/about'
    | '/bi'
    | '/dataanalyst'
    | '/excel'
    | '/interview-questions'
    | '/practice'
    | '/projects'
    | '/python'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/sql'
    | '/roadmaps/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Statistics'
    | '/about'
    | '/bi'
    | '/dataanalyst'
    | '/excel'
    | '/interview-questions'
    | '/practice'
    | '/projects'
    | '/python'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/sql'
    | '/roadmaps/$slug'
  id:
    | '__root__'
    | '/'
    | '/Statistics'
    | '/about'
    | '/bi'
    | '/dataanalyst'
    | '/excel'
    | '/interview-questions'
    | '/practice'
    | '/projects'
    | '/python'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/sql'
    | '/roadmaps/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatisticsRoute: typeof StatisticsRoute
  AboutRoute: typeof AboutRoute
  BiRoute: typeof BiRoute
  DataanalystRoute: typeof DataanalystRoute
  ExcelRoute: typeof ExcelRoute
  InterviewQuestionsRoute: typeof InterviewQuestionsRoute
  PracticeRoute: typeof PracticeRoute
  ProjectsRoute: typeof ProjectsRoute
  PythonRoute: typeof PythonRoute
  ResourcesRoute: typeof ResourcesRoute
  RoadmapsRoute: typeof RoadmapsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SqlRoute: typeof SqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Statistics': {
      id: '/Statistics'
      path: '/Statistics'
      fullPath: '/Statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataanalyst': {
      id: '/dataanalyst'
      path: '/dataanalyst'
      fullPath: '/dataanalyst'
      preLoaderRoute: typeof DataanalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel': {
      id: '/excel'
      path: '/excel'
      fullPath: '/excel'
      preLoaderRoute: typeof ExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-questions': {
      id: '/interview-questions'
      path: '/interview-questions'
      fullPath: '/interview-questions'
      preLoaderRoute: typeof InterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/$slug': {
      id: '/roadmaps/$slug'
      path: '/$slug'
      fullPath: '/roadmaps/$slug'
      preLoaderRoute: typeof RoadmapsSlugRouteImport
      parentRoute: typeof RoadmapsRoute
    }
  }
}

interface RoadmapsRouteChildren {
  RoadmapsSlugRoute: typeof RoadmapsSlugRoute
}

const RoadmapsRouteChildren: RoadmapsRouteChildren = {
  RoadmapsSlugRoute: RoadmapsSlugRoute,
}

const RoadmapsRouteWithChildren = RoadmapsRoute._addFileChildren(
  RoadmapsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatisticsRoute: StatisticsRoute,
  AboutRoute: AboutRoute,
  BiRoute: BiRoute,
  DataanalystRoute: DataanalystRoute,
  ExcelRoute: ExcelRoute,
  InterviewQuestionsRoute: InterviewQuestionsRoute,
  PracticeRoute: PracticeRoute,
  ProjectsRoute: ProjectsRoute,
  PythonRoute: PythonRoute,
  ResourcesRoute: ResourcesRoute,
  RoadmapsRoute: RoadmapsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SqlRoute: SqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
